app1/urls.py
from app1.views import *
from django.urls import path
app_name='hitman'
urlpatterns=[
path('rohit/',rohit,name='rohit'),

]

app2/urls.py
from app2.views import *
from django.urls import path
app_name='king'


urlpatterns=[

 path('kohli/',kohli,name='kohli'),

]

project13/urls.py
from django.contrib import admin
from django.urls import path,include
import app1,app2


urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
    path('app2/',include('app2.urls')),
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.
def rohit(request):
    return render(request,'rohit.html')

app2/views.py
from django.shortcuts import render

# Create your views here.
def kohli(request):
    return render(request,'kohli.html')

templates/kohli.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>kohli lifted the call</h1>
        <h1>hai rohit bhai kya call  kar diya</h1>
        <h1>next time we will  win the world cup</h1>
       <h1> <a href="{% url 'hitman:rohit' %}">navigating to rohit</a></h1>
    </center>
</body>
</html>

templates/rohit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>rohit calling to kohli</h1>
        <h1>haa haa we will win the world cup lets come back stronger</h1>
       <h1> <a href="{% url 'king:kohli' %}">calling to kohli</a></h1>
    </center>
</body>
</html>